#!/usr/bin/env bash
# Configuration Generator Utility
# Handles --config-gen flag and template generation

# Generate a comprehensive config template
generate_config_template() {
    local config_name="$1"
    local config_file="$INSTA_TOPLVL/insta/confs/${config_name}.sh"

    cat > "$config_file" << EOF
# Configuration template generated by --config-gen
# Edit this file with your desired settings, then run the installer with --config ${config_name}

# Configuration name (used for skel directory)
export CONFIG_NAME="${config_name}"

# Disk configuration
export TARGET_DISK="/dev/sda"
export TARGET_DIR="/target"

# External drives configuration (uncomment and modify as needed)
# These drives will be partitioned (single partition), formatted as XFS, and mounted during installation
# Format: DEVICE:MOUNTPOINT:LABEL
# DEVICE should be the whole drive (e.g., /dev/sdb)
# export EXTERNAL_DRIVES=(
#     "/dev/sdb:/drv/data:data"
#     "/dev/sdc:/mnt/backup:backup"
# )

# Preserve drives configuration (uncomment and modify as needed)
# These drives will be mounted but NOT reformatted during installation
# Useful for preserving existing data partitions
# Format: DEVICE:MOUNTPOINT
# DEVICE can be /dev/sdx, LABEL=label, or UUID=uuid
# export PRESERVE_DRIVES=(
#     "LABEL=room:/room"
#     "LABEL=data:/drv/data"
#     "UUID=12345678-1234-1234-1234-123456789abc:/mnt/backup"
# )

# System configuration
export TIMEZONE="America/Chicago"
export LOCALE="en_US.UTF-8"
export KEYMAP="colemak"
export HOSTNAME="hostname"
export USERNAME="username"
export HOMEDIR="/home/username"
export PASSWORD="changeme"
export PASSROOT="changeme"

# Software configuration
export KERNEL="linux-lts"
export DESKTOP="plasma"  # plasma, hyprland, none
export GPU_DRIVER="auto"  # auto, nvidia, nvidia-lts, amd, intel, modesetting

# Additional packages (appended to defaults)
export EXTRA_PACKAGES=(
    # Add your extra packages here
)

# AUR packages to install
export AUR_PACKAGES=(
    # Add your AUR packages here
)

# Additional services to enable
export SERVICES=""

# Boot options (appended to kernel command line)
# export BOOT_OPTIONS="fbcon=rotate:2"

# Installation options
# export AUTO_CHROOT_CONFIRM="false"

# Full package/service overrides (replaces defaults entirely)
# export BASE_PACKAGES="base linux-lts linux-firmware base-devel networkmanager openssh"
# export EXTRA_PACKAGES="htop neofetch vim git"
# export AUR_PACKAGES="your-aur-package"
# export SERVICES="NetworkManager fstrim.timer reflector.timer"
EOF
}

# Create skeleton directory structure
create_skeleton_structure() {
    local config_name="$1"
    local skel_dir="$INSTA_TOPLVL/insta/skel/${config_name}"

    mkdir -p "$skel_dir/@sys"
    mkdir -p "$skel_dir/@root"
    mkdir -p "$skel_dir/@user"

    # Create README in the skeleton directory
    cat > "$skel_dir/README.md" << EOF
# ${config_name} Configuration Skeleton

This directory contains configuration files that will be copied during installation.

## Directory Structure:
- **@sys/** - Files copied to system root (/)
- **@root/** - Files copied to root user's home (/root/)
- **@user/** - Files copied to configured user's home

## Usage:
Place configuration files in the appropriate directories above.
They will be automatically copied during the installation process.

Example:
- @sys/etc/systemd/system/my-service.service
- @user/.config/my-app/config.ini
- @root/.zshrc
EOF
}

# Handle --config-gen flag
handle_config_gen() {
    local config_name="${1:-template}"
    generate_config_template "$config_name"
    create_skeleton_structure "$config_name"
    echo "Generated config template: insta/confs/${config_name}.sh"
    echo "Created skeleton structure: insta/skel/${config_name}/"
    echo "Edit the config and skeleton files as needed, then run: $0 --config ${config_name}"
    exit 0
}