# Configuration template generated by --config-gen
# Edit this file with your desired settings, then run the installer with --config template

# Configuration name (used for skel directory)
export CONFIG_NAME="template"

# Disk configuration
export TARGET_DISK="/dev/sda"
export TARGET_DIR="/target"

# External drives configuration (uncomment and modify as needed)
# These drives will be partitioned (single partition), formatted as XFS, and mounted during installation
# Format: DEVICE:MOUNTPOINT:LABEL
# DEVICE should be the whole drive (e.g., /dev/sdb)
# export EXTERNAL_DRIVES=(
#     "/dev/sdb:/drv/data:data"
#     "/dev/sdc:/mnt/backup:backup"
# )

# Preserve drives configuration (uncomment and modify as needed)
# These drives will be mounted but NOT reformatted during installation
# Useful for preserving existing data partitions
# Format: DEVICE:MOUNTPOINT
# DEVICE can be /dev/sdx, LABEL=label, or UUID=uuid
# export PRESERVE_DRIVES=(
#     "LABEL=room:/room"
#     "LABEL=data:/drv/data"
#     "UUID=12345678-1234-1234-1234-123456789abc:/mnt/backup"
# )

# System configuration
export TIMEZONE="America/Chicago"
export LOCALE="en_US.UTF-8"
export KEYMAP="colemak"
export HOSTNAME="hostname"
export USERNAME="username"
export HOMEDIR="/home/username"
export PASSWORD="changeme"
export PASSROOT="changeme"

# Software configuration
export KERNEL="linux-lts"
export DESKTOP="plasma"  # plasma, hyprland, none
export GPU_DRIVER="auto"  # auto, nvidia, nvidia-lts, amd, intel, modesetting

# Additional packages (appended to defaults)
export EXTRA_PACKAGES=(
    # Add your extra packages here
)

# AUR packages to install
export AUR_PACKAGES=(
    # Add your AUR packages here
)

# Additional services to enable
export SERVICES=""

# Boot options (appended to kernel command line)
# export BOOT_OPTIONS="fbcon=rotate:2"

# Installation options


# Full package/service overrides (replaces defaults entirely)
# export BASE_PACKAGES="base linux-lts linux-firmware base-devel networkmanager openssh"
# export EXTRA_PACKAGES="htop neofetch vim git"
# export AUR_PACKAGES="your-aur-package"
# export SERVICES="NetworkManager fstrim.timer reflector.timer"
